fragment Info on Info {
  count
  pages
  next
  prev
}

query getCharecters($page: Int, $filter: FilterCharacter) {
  characters(page: $page, filter: $filter) {
    info {
      ...Info
    }
    results {
      id
      name
      status
      species
      type
      gender
      origin {
        id
        name
        type
      }
    }
  }
}
