fragment Info on Info {
  count
  next
  prev
}

query getCharecters($page: Int) {
  characters(page: $page) {
    info {
      ...Info
    }
    results {
      id
      name
      species
      origin {
        name
      }
      location {
        name
      }
    }
  }
}
