query getEpisodes($page: Int) {
  episodes(page: $page) {
    info {
      ...Info
    }
    results {
      id
      episode
      name
      air_date
    }
  }
}

query getEpisodesByIds($ids: [ID!]!) {
  episodesByIds(ids: $ids) {
    id
    episode
    name
    air_date
    characters {
      id
      name
      species
      origin {
        name
      }
      location {
        name
      }
    }
  }
}
