query getLocations($page: Int) {
  locations(page: $page) {
    info {
      ...Info
    }
    results {
      id
      name
      type
      dimension
    }
  }
}

query getLocationsByIds($ids: [ID!]!) {
  locationsByIds(ids: $ids) {
    id
    name
    type
    dimension
    residents {
      id
      name
      species
      origin {
        name
      }
      location {
        name
      }
    }
  }
}
